name: Update README

on:
  schedule:
    - cron: '0 23 * * 6'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update this repo's README with recent activity
    steps:
     - name: repo checkout
       uses: actions/checkout@v2
     
     - name: git activity readme
       uses: Readme-Workflows/recent-activity@main
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
        CONFIG_FILE: '.github/recent-activity.config.yml'
        COMMIT_MSG: "Updated README with recent activity"
        MAX_LINES: 10
